<?php
/**
 * Inbox View/Template.
 *
 * This file displays the user's received messages (Inbox) within the messaging module
 * of the 'mjschool' plugin. It handles message listing, pagination, and links to view
 * individual messages.
 *
 * Key features include:
 * - **Security:** Checks and verifies a nonce (`mjschool_message_tab`) for security on tab navigation.
 * - **Pagination:** Implements custom pagination logic to handle large numbers of messages (`mjschool_inbox_pagination`).
 * - **Message Display:** Fetches and displays a list of messages, showing sender, subject, date, and attachments.
 * - **Attachment Links:** Provides links to view or download message attachments stored in the school assets folder.
 * - **Unread Count:** Displays the total count of unread messages.
 *
 * @package    Mjschool
 * @subpackage Mjschool/templates
 * @since      1.0.0
 */
defined( 'ABSPATH' ) || exit;

// Check nonce for inbox tab.
if ( isset( $_GET['tab'] ) ) {
	if ( ! isset( $_GET['_wpnonce'] ) || ! wp_verify_nonce( sanitize_text_field(wp_unslash($_GET['_wpnonce'])), 'mjschool_message_tab' ) ) {
		wp_die( esc_html__( 'Security check failed. Please reload the page.', 'mjschool' ) );
	}
}

$message = mjschool_count_inbox_item( get_current_user_id() );
$max     = 10;
if ( isset( $_GET['pg'] ) ) {
	$p = intval(wp_unslash($_GET['pg']));
} else {
	$p = 1;
}
$limit          = ( $p - 1 ) * $max;
$prev           = $p - 1;
$next           = $p + 1;
$limits         = (int) ( $p - 1 ) * $max;
$totlal_message = count( $message );
$totlal_message = ceil( $totlal_message / $max );
$lpm1           = $totlal_message - 1;
$offest_value   = ( $p - 1 ) * $max;
// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- HTML is safely generated by a trusted internal function
echo mjschool_inbox_pagination( $totlal_message, $p, $lpm1, $prev, $next );
$message = mjschool_get_inbox_message( get_current_user_id(), $limit, $max );
?>
<div class="mjschool-mailbox-content">
	<?php
	if ( ! empty( $message ) ) {
		?>
		<div class="table-responsive" id="sentbox_table">
			<form name="wcwm_report" action="" method="post"><!-- Form-div. -->
				<table class="table" id="frontend_inbox_list">
					<thead class="<?php echo esc_attr( mjschool_datatable_header() ); ?>">
						<tr>
							<th><?php esc_html_e( 'Image', 'mjschool' ); ?></th>
							<th><?php esc_html_e( 'Message From', 'mjschool' ); ?></th>
							<th><?php esc_html_e( 'Message For', 'mjschool' ); ?></th>
							<th><?php esc_html_e( 'Subject', 'mjschool' ); ?></th>
							<th><?php esc_html_e( 'Description', 'mjschool' ); ?></th>
							<th><?php esc_html_e( 'Attachment', 'mjschool' ); ?></th>
							<th><?php esc_html_e( 'Date & Time', 'mjschool' ); ?></th>
						</tr>
					</thead>
					<tbody>	
						<?php
						$message = mjschool_get_inbox_message( get_current_user_id(), $limit, $max );
						if ( ! empty( $message ) ) {
							$i = 0;
							foreach ( $message as $msg ) {
								$color_class_css = mjschool_table_list_background_color( $i );
								$message_for = get_post_meta( $msg->post_id, 'message_for', true );
								$attchment   = get_post_meta( $msg->post_id, 'message_attachment', true );
								if ( $message_for === 'student' || $message_for === 'supportstaff' || $message_for === 'teacher' || $message_for === 'parent' ) {
									$post_id = '';
									if ( $post_id === $msg->post_id ) {
										continue;
									} else {
										?>
										<tr>
											<td class="mjschool-user-image mjschool-width-50px-td mjschool-profile-image-prescription mjschool-padding-left-0">
												<p class="mjschool-prescription-tag mjschool-padding-15px mjschool-margin-bottom-0px <?php echo esc_attr( $color_class_css ); ?>">	
													<img src="<?php echo esc_url( MJSCHOOL_PLUGIN_URL."/assets/images/dashboard-icon/icons/white-icons/mjschool-inbox.png")?>" height= "30px" width ="30px" class="mjschool-massage-image">
												</p>
											</td>	
											<td>
												<a href="<?php echo esc_url( '?dashboard=mjschool_user&page=message&tab=view_message&from=inbox&id=' . mjschool_encrypt_id( $msg->message_id ) ); ?>" class="mjschool-text-decoration-none">
													<?php
													$auth   = get_post( $msg->post_id );
													$authid = $auth->post_author;
													echo esc_html( mjschool_get_display_name( $authid ) );
													?>
												</a> 
												<i class="fa-solid fa-circle-info mjschool-fa-information-bg" data-toggle="tooltip" data-placement="top" title="<?php esc_attr_e( 'Message From', 'mjschool' ); ?>"></i>
											</td>	
											<td>
												<a href="<?php echo esc_url( '?dashboard=mjschool_user&page=message&tab=view_message&from=inbox&id=' . mjschool_encrypt_id( $msg->message_id ) ); ?>" class="mjschool-text-decoration-none">
													<?php
													$check_message_single_or_multiple = mjschool_send_message_check_single_user_or_multiple( $msg->post_id );
													if ( $check_message_single_or_multiple === 1 ) {
														$post_id  = $msg->post_id;
														$get_single_user = mjschool_get_message_by_post_id($post_id );
														echo esc_html(mjschool_get_display_name($get_single_user->receiver));
													} else {
														echo esc_html( get_post_meta( $msg->post_id, 'message_for', true ) );
													}
													?>
												</a> 
												<i class="fa-solid fa-circle-info mjschool-fa-information-bg" data-toggle="tooltip" data-placement="top" title="<?php esc_attr_e( 'Message For', 'mjschool' ); ?>"></i>	
												<?php
												$unread_count = mjschool_count_unread_message_current_user( $msg->post_id );
												if ( $unread_count > 0 ) :
													?>
													<span class="badge badge-success ms-1 mjschool_background_color_purple" >
														<?php echo esc_html( $unread_count ); ?>
													</span>
												<?php endif; ?>
											</td>
											<td>
												<a href="<?php echo esc_url( '?dashboard=mjschool_user&page=message&tab=view_message&from=inbox&id=' . mjschool_encrypt_id( $msg->message_id ) ); ?>" class="mjschool-text-decoration-none mjschool-inbox-tab">
													<?php
													$obj_message = new Mjschool_Message();
													$msg_post_id = $obj_message->mjschool_count_reply_item( $msg->post_id );
													$subject_char = strlen( $msg->subject );
													if ( $subject_char <= 10 ) {
														echo esc_html( $msg->subject );
													} else {
														$char_limit   = 10;
														$subject_body = substr( strip_tags( $msg->subject ), 0, $char_limit ) . '...';
														echo esc_html( $subject_body );
													}
													if ( $msg_post_id >= 1 ) {
														?>
														<span class="mjschool-inbox-count-number badge badge-success  pull-right ms-1"><?php echo esc_html( $msg_post_id ); ?></span>
													<?php } ?>
												</a>
												<i class="fa-solid fa-circle-info mjschool-fa-information-bg" data-toggle="tooltip" data-placement="top" title="<?php if ( ! empty( $msg->subject ) ) { echo esc_html( $msg->subject ); } else { esc_html_e( 'Subject', 'mjschool' );} ?>"></i>       
											</td>
											<td>
												<?php
												$body_char = strlen( $msg->message_body );
												if ( $body_char <= 40 ) {
													echo esc_html( $msg->message_body );
												} else {
													$char_limit = 40;
													$msg_body   = substr( strip_tags( $msg->message_body ), 0, $char_limit ) . '...';
													echo esc_html( $msg_body );
												}
												?>
												<i class="fa-solid fa-circle-info mjschool-fa-information-bg" data-toggle="tooltip" data-placement="top" title="<?php if ( $msg->message_body ) { echo esc_html( $msg->message_body ); } else { esc_html_e( 'Description', 'mjschool' );} ?>"></i>   
											</td>
											<td>	
												<?php
												if ( ! empty( $attchment ) ) {
													$attchment_array = explode( ',', $attchment );
													foreach ( $attchment_array as $attchment_data ) {
														?>
														<a target="blank" href="<?php echo esc_url( content_url( '/uploads/school_assets/' . $attchment_data )); ?>" class="btn btn-default"><i class="fas fa-download"></i> <?php esc_html_e( 'View Attachment', 'mjschool' ); ?></a>
														<?php
													}
												} else {
													esc_html_e( 'No Attachment', 'mjschool' );
												}
												?>
											</td>
											<td>
												<a href="<?php echo esc_url( '?dashboard=mjschool_user&page=message&tab=view_message&from=inbox&id=' . mjschool_encrypt_id( $msg->message_id ) ); ?>" class="mjschool-text-decoration-none">	
													<?php echo esc_html( mjschool_convert_date_time( $msg->date ) ); ?>
												</a> 
												<i class="fa-solid fa-circle-info mjschool-fa-information-bg" data-toggle="tooltip" data-placement="top" title="<?php esc_attr_e( 'Date & Time', 'mjschool' ); ?>"></i>
											</td>
										</tr>
										<?php
										++$i;
									}
								} else {
									?>
									<tr>
										<td class="mjschool-user-image mjschool-width-50px-td mjschool-profile-image-prescription mjschool-padding-left-0">
											<p class="mjschool-prescription-tag mjschool-padding-15px mjschool-margin-bottom-0px <?php echo esc_attr( $color_class_css ); ?>">
												<img src="<?php echo esc_url( MJSCHOOL_PLUGIN_URL."/assets/images/dashboard-icon/icons/white-icons/mjschool-inbox.png")?>" height= "30px" width ="30px" class="mjschool-massage-image">
											</p>
										</td>	
										<td>
											<a href="<?php echo esc_url( '?dashboard=mjschool_user&page=message&tab=view_message&from=inbox&id=' . mjschool_encrypt_id( $msg->message_id ) ); ?>" class="mjschool-text-decoration-none">
												<?php
												$auth   = get_post( $msg->post_id );
												$authid = $auth->post_author;
												echo esc_html( mjschool_get_display_name( $authid ) );
												?>
											</a>
										</td>	
										<td>
											<a href="<?php echo esc_url( '?dashboard=mjschool_user&page=message&tab=view_message&from=inbox&id=' . mjschool_encrypt_id( $msg->message_id ) ); ?>" class="mjschool-text-decoration-none">
												<?php
												$check_message_single_or_multiple = mjschool_send_message_check_single_user_or_multiple( $msg->post_id );
												if ( $check_message_single_or_multiple === 1 ) {
													$post_id  = $msg->post_id;
													$get_single_user = mjschool_get_message_by_post_id($post_id );
													echo esc_html( mjschool_get_display_name( $get_single_user->receiver ) );
												} else {
													echo esc_html( get_post_meta( $msg->post_id, 'message_for', true ) );
												}
												?>
											</a>
										</td>
										<td>
											<a href="<?php echo esc_url( '?dashboard=mjschool_user&page=message&tab=view_message&from=inbox&id=' . mjschool_encrypt_id( $msg->message_id ) ); ?>" class="mjschool-text-decoration-none"> 
												<?php echo esc_html( $msg->subject ); ?>
												<?php
												$obj_message = new Mjschool_Message();
												$msg_post_id = $obj_message->mjschool_count_reply_item( $msg->post_id );
												$subject_char = strlen( $msg->subject );
												if ( $subject_char <= 10 ) {
													echo esc_html( $msg->subject );
												} else {
													$char_limit   = 10;
													$subject_body = substr( strip_tags( $msg->subject ), 0, $char_limit ) . '...';
													echo esc_html( $subject_body );
												}
												if ( $msg_post_id >= 1 ) {
													?>
													<span class="badge badge-success pull-right"><?php echo esc_html( $msg_post_id ); ?></span>
												<?php } ?>
											</a>
										</td>
										<td>
											<a href="<?php echo esc_url( '?dashboard=mjschool_user&page=message&tab=view_message&from=inbox&id=' . mjschool_encrypt_id( $msg->message_id ) ); ?>" class="mjschool-text-decoration-none">
												<?php
												$body_char = strlen( $msg->message_body );
												if ( $body_char <= 60 ) {
													echo esc_html( $msg->message_body );
												} else {
													$char_limit = 60;
													$msg_body   = substr( strip_tags( $msg->message_body ), 0, $char_limit ) . '...';
													echo esc_html( $msg_body );
												}
												?>
											</a>
										</td>
										<td>	
											<?php
											if ( ! empty( $attchment ) ) {
												$attchment_array = explode( ',', $attchment );
												foreach ( $attchment_array as $attchment_data ) {
													?>
													<a target="blank" href="<?php echo esc_url( content_url( '/uploads/school_assets/' . $attchment_data )); ?>" class="btn btn-default"><i class="fas fa-eye"></i> <?php esc_html_e( 'View Attachment', 'mjschool' ); ?></a>
													<?php
												}
											} else {
												esc_html_e( 'No Attachment', 'mjschool' );
											}
											?>
										</td>
										<td>
											<a href="<?php echo esc_url( '?dashboard=mjschool_user&page=message&tab=view_message&from=inbox&id=' . mjschool_encrypt_id( $msg->message_id ) ); ?>" class="mjschool-text-decoration-none"> <?php echo esc_html( mjschool_convert_date_time( $msg->date ) ); ?> </a>
										</td>
									</tr>
									<?php
								}
								$post_id = $msg->post_id;
							}
						} else {
							?>
							<tr>
								<td colspan="6" class="mjschool-table-empty-message"> <?php esc_html_e( 'No data available in table', 'mjschool' ); ?> </td>
							</tr>
							<?php
						}
						?>
					</tbody>
				</table>
			</form><!-- Form-div. -->
		</div>
		<?php
	} else {
		 ?>
		<div class="mjschool-calendar-event-new"> 
			<img class="mjschool-no-data-img" src="<?php echo esc_url(MJSCHOOL_NODATA_IMG)?>" alt="<?php esc_html_e( 'No data', 'mjschool' ); ?>">
		</div>	
		<?php 
	}
	?>
</div>